<?php
session_start();
include("conn.php");

if (isset($_SESSION['gymafi_coachid'])) {
  header("location: dashboard.php");
} else if (isset($_SESSION['gymafi_superadmin'])) {
  header("location: admin/superadmin.php");
} else if (
  !(isset($_SESSION['gymafi_coachid'])) && !(isset($_SESSION['gymafi_superadmin']))
  && !(isset($_SESSION['gymafi_userid']))
) {
  header("location: login.php");
}
$userid = $_SESSION['gymafi_userid']; // else, save user id as local variable


/**
 * Gets all of the details of the user who is currently logged in,
 * to display on their profile page as well as to fill the values of the edit profile modals.
 */
$selectUser = $conn->prepare("SELECT webdev_users.username, webdev_users.date_of_birth, webdev_users.email, webdev_user_details.name, 
webdev_user_details.address,  webdev_user_details.postcode,  webdev_user_details.city,  
webdev_user_details.phone_number, webdev_user_stats.starting_weight, webdev_user_details.picture, 
webdev_user_stats.height, webdev_user_stats.weight_current, 
webdev_user_stats.BMI_current, webdev_user_stats.body_fat_current, 
webdev_user_stats.weight_goal, webdev_user_stats.BMI_goal, webdev_user_stats.body_fat_goal
FROM webdev_users 
INNER JOIN webdev_user_details 
ON webdev_users.id = webdev_user_details.user_id 
INNER JOIN webdev_user_stats
ON webdev_users.id = webdev_user_stats.user_id
WHERE webdev_users.id  = ?");
$selectUser->bind_param("i", $userid);
$selectUser->execute();
$selectUser->store_result();
$selectUser->bind_result(
  $username,
  $dateOfBirth,
  $userEmail,
  $userActualName,
  $userAddress,
  $userPostcode,
  $userCity,
  $userPhoneNumber,
  $startingWeight,
  $userPicture,
  $raw_height,
  $currentWeight,
  $currentBMI,
  $currentBFat,
  $goalWeight,
  $goalBMI,
  $goalBFat
);
$selectUser->fetch();

// generate some additional variables from data gathered from db.
$age = date_diff(date_create($dateOfBirth), date_create('now'))->y;
$weightLost = ((intval($startingWeight)) - intval($currentWeight));
$height = number_format($raw_height, 1, '.', '');


//user pic is optional, if empty sets to defaut image
if ($userPicture == "" || !$userPicture) {
  $userPicture = "default_pic.png";
}

//get all details of user training regime in a similar vein as above
$getTrainingReg = $conn->prepare("SELECT diet_plan, monday, tuesday, wednesday, thursday, friday, saturday, sunday
 FROM webdev_training_regime 
 WHERE user_id = ?");


$getTrainingReg->bind_param("i", $userid);
$getTrainingReg->execute();
$getTrainingReg->store_result();
$getTrainingReg->bind_result(
  $currentDiet,
  $currentMonday,
  $currentTuesday,
  $currentWednesday,
  $currentThursday,
  $currentFriday,
  $currentSatuday,
  $currentSunday
);
$getTrainingReg->fetch();


/**
 * Attempts to change the details of the user.
 * Captures and sanitises the posted data.
 * If all fields have been successfully posted, checks they meet the validation checks. 
 * Checks the values have been changes, so there is at least one change, and that they are numeric.
 * If it passes all checks, submits the change to the details.
 */
if (isset($_POST['detailsSubmit'])) {

  function check_your_datetime($x)
  {
    return (date('Y-m-d H:i:s', strtotime($x)) == $x);
  }

  $updatedUsername = $_POST['newUsername'];
  $sanitisedUsername = $conn->real_escape_string(trim($updatedUsername));

  $updatedName = $_POST['newName'];
  $sanitisedName = $conn->real_escape_string(trim($updatedName));
  $updatedEmail = $_POST['newEmail'];
  $sanitisedEmail = $conn->real_escape_string(trim($updatedEmail));
  $updatedPhoneNumber = $_POST['newNumber'];
  $sanitisedPhoneNumber = $conn->real_escape_string(trim($updatedPhoneNumber));
  $updatedAddress = $_POST['newAddressOne'];
  $sanitisedAddress = $conn->real_escape_string(trim($updatedAddress));
  $updatedCity = $_POST['newCity'];
  $sanitisedCity = $conn->real_escape_string(trim($updatedCity));
  $updatedPostcode = $_POST['newPostcode'];
  $sanitisedPostcode = $conn->real_escape_string(trim($updatedPostcode));
  $postedDOB = $_POST['updateDOB'];
  $updatedDOB = date('Y-m-d', strtotime($postedDOB));
  $sanitisedDOB = $conn->real_escape_string(trim($updatedDOB));
  $newPicPath = $_POST['changePic'];
  $sanitisedPicPath = $conn->real_escape_string(trim($newPicPath));

  /*
  * Explodes DOB entered by user and a new date generated by server (today's date). 
  If user DOB entered is < 18, does not allow this to update.
  * Adapted from <https://stackoverflow.com/questions/4529640/get-the-year-from-specified-date-php/4529680>
  */
  $todaysDate = date('Y-m-d');
  $yearOfDOB = explode('-', $sanitisedDOB);
  $DOBYear = $yearOfDOB[0];
  $todayExplode = explode('-', $todaysDate);
  $todayYear = $todayExplode[0];
  $minimumYear = ($todayYear - 18);





  /**
   * Determines all fields have been changed. If all the same, does not send query and outputs error message.
   * 
   * If phone number is not numeric outputs error and does not send query
   * (phone number is stored as varchar in db - due to issues with it being an int, 
   *  such removing the first 0, value of a normal phone number > int value allowed).
   * 
   * If name and city fields are not wholly alphabetical, output error and does not send query.
   * 
   * Else, if all is okay it sends the query and a success message is sent.
   * 
   */
  if (($updatedUsername == $username) && ($updatedEmail == $userEmail)
    &&  ($updatedName == $userActualName) && ($updatedAddress == $userAddress) &&
    ($postedDOB == $dateOfBirth) &&
    ($updatedPostcode == $userPostcode) &&
    ($updatedPhoneNumber == $userPhoneNumber) &&
    ($updatedCity == $userCity)  && ($newPicPath == $userPicture)
  ) {
    $updateFailed = "Your details have not been updated - you have not changed any fields.";
  } else if (preg_match('~[0-9]~', $sanitisedName)) {
    $updateFailed = "Your details have not been updated - name must only contain letters.";
  } else if (!ctype_digit($sanitisedPhoneNumber)) {
    $updateFailed = "Your details have not been updated - phone number not numeric.";
  } else if (preg_match('~[0-9]~', $sanitisedCity)) {
    $updateFailed = "Your details have not been updated - city must contain letters.";
  } else if ((strlen($sanitisedUsername) > 25)) {
    $updateFailed = "Error with updating username - username out of range boundary. Must be under 25 characters.";
  } else if ((strlen($sanitisedName) > 35)) {
    $updateFailed = "Error with updating name - name out of range boundary. Must be under 35 characters.";
  } else if ((strlen($sanitisedEmail) > 35)) {
    $updateFailed = "Error with updating email - email out of range boundary. Must be under 55 characters.";
  } else if ((strlen($updatedPhoneNumber) < 10) || strlen($updatedPhoneNumber) > 13) {
    $updateFailed = "Error with sign up - telephone number out of range boundary. Must be between 10 - 13 digits.";
  } else if ((strlen($sanitisedCity) > 35)) {
    $updateFailed = "Error with sign up - city  out of range boundary. Must be under 35 characters.";
  } else if ((strlen($sanitisedAddress) > 100)) {
    $updateFailed = "Error with sign up - address  out of range boundary. Must be under 100 characters.";
  } else if ((strlen($sanitisedPostcode) > 10)) {
    $updateFailed = "Error with sign up - postcode  out of range boundary. Must be under 10 characters.";
  } else if ($DOBYear > $minimumYear) {
    $updateFailed = "Your details have not been updated - you must be over 18.";
  } else if (($sanitisedUsername == null) || ($sanitisedEmail == null)
    || ($sanitisedName == null) || ($sanitisedAddress == null) ||
    ($sanitisedDOB == null) ||  ($sanitisedPostcode == null)
    ||  ($sanitisedPhoneNumber == null) ||  ($sanitisedCity == null)

  ) {
    $updateFailed = "Your details have not been updated - null fields submitted.";
  } else {
    // transaction adapted from online tutorial <https://www.youtube.com/watch?v=CNt9HPqDIVc>
    $conn->autocommit(false);

    $error = array();

    $a = $conn->query("UPDATE webdev_users 
SET webdev_users.username = '$sanitisedUsername', webdev_users.email = '$sanitisedEmail', webdev_users.date_of_birth = '$sanitisedDOB'
WHERE webdev_users.id = '$userid'");
    if ($a == false) {
      array_push($error, 'Problem updating user details');
      echo $conn->error;
    }
    $b = $conn->query("UPDATE webdev_user_details SET webdev_user_details.name = '$sanitisedName', 
webdev_user_details.address = '$sanitisedAddress',  webdev_user_details.postcode = '$sanitisedPostcode',  
webdev_user_details.city = '$sanitisedCity',   webdev_user_details.phone_number = '$sanitisedPhoneNumber', webdev_user_details.picture = '$sanitisedPicPath'
WHERE webdev_user_details.user_id = '$userid'");
    if ($b == false) {
      array_push($error, 'Problem updating user details.');
      echo $conn->error;
    }

    /**
     * If error array is empty, something has gone wrong - rollback occurs.
     */
    if (!empty($error)) {
      $conn->rollback();
    } else {

      //commit if all ok
      $conn->commit();
      $updateSuccessful = "Your details have successfully been updated.";
    }
  }
} // end of checking if the update for personal details is set

/**
 * Attempts to change the progress of the user.
 * Captures and sanitises the posted data.
 * If all fields have been successfully posted, checks they meet the validation checks. 
 * Checks the values have been changes, so there is at least one change, and that they are numeric.
 * If it passes all checks, submits the change to the progress.
 */

if (isset($_POST['progressSubmit'])) {
  $updateheight = $_POST['height'];
  $sanitisedHeight = $conn->real_escape_string(trim($updateheight));
  $formatted_height = number_format($sanitisedHeight, 1, '.', '');


  $updateCWeight = $_POST['cWeight'];
  $sanitisedCWeight = $conn->real_escape_string(trim($updateCWeight));
  $formatted_CWeight = number_format($sanitisedCWeight, 1, '.', '');

  $updateSWeight = $_POST['sWeight'];
  $sanitisedUdateSWeight = $conn->real_escape_string(trim($updateSWeight));
  $formatted_SWeight = number_format($sanitisedUdateSWeight, 1, '.', '');


  $updateCBMI = $_POST['cBMI'];
  $sanitisedUpdateCBMI = $conn->real_escape_string(trim($updateCBMI));
  $formatted_CBMI = number_format($sanitisedUpdateCBMI, 1, '.', '');



  $updateCBFat = $_POST['cBFat'];
  $sanitisedUpdateCBFat  = $conn->real_escape_string(trim($updateCBFat));
  $formatted_CBFat = number_format($sanitisedUpdateCBFat, 1, '.', '');
  $minHeight = 120.0;
  $maxHeight = 213.0;


  $updateCurrent = "UPDATE webdev_user_stats
  SET webdev_user_stats.height = '$sanitisedHeight', webdev_user_stats.starting_weight ='$sanitisedUdateSWeight', 
  webdev_user_stats.weight_current = '$sanitisedCWeight',  webdev_user_stats.BMI_current = '$sanitisedUpdateCBMI', 
  webdev_user_stats.body_fat_current = '$sanitisedUpdateCBFat'
  WHERE webdev_user_stats.user_id = '$userid'";


  /**
   * Determines all fields have been changed. If all the same, does not send query and outputs error message.
   * If height, weight, bmi or body fat values are not numeric it displays an error and does not send query.
   * Else, if all is okay it sends the query and a success message is sent.
   */
  if (($height == $updateheight) && ($currentWeight == $updateCWeight) &&
    ($currentBMI == $updateCBMI) && ($currentBFat == $updateCBFat) &&
    ($startingWeight == $sanitisedUdateSWeight)
  ) {
    $updateFailed = "Your details have not been updated - you have not changed any fields.";
  } else if (!is_numeric($formatted_height)) {
    $updateFailed = "Your details have not been updated - height must be numeric.";
  } else if (($updateheight < $minHeight) || ($updateheight > $maxHeight)) {
    $updateFailed = "Your details have not been updated - height must be between 140 - 213 cm (1.4m - 2.13m).";
  } else if (!is_numeric($updateSWeight)) {
    $updateFailed = "Your details have not been updated - starting weight must be numeric.";
  } else if (!is_numeric($updateCWeight)) {
    $updateFailed = "Your details have not been updated - current weight must be numeric.";
  } else if (!is_numeric($updateCBMI)) {
    $updateFailed = "Your details have not been updated - current BMI must be numeric.";
  } else if (!is_numeric($sanitisedUpdateCBFat)) {
    $updateFailed = "Your details have not been updated - current body fat (%) must be numeric.";
  } else if ($sanitisedUpdateCBFat < 1.0 || $sanitisedUpdateCBFat > 60.0) {
    $updateFailed = "Your details have not been updated - current body fat (%) must be between 1.0 - 60.0.";
  } else {
    $executeUpdateCurrent = $conn->query($updateCurrent);

    if (!$executeUpdateCurrent) {
      echo $conn->error;
      $updateFailed = "Error with changing current details.";
    }
    $updateSuccessful = "Your details have successfully been updated.";
  }
} // end of checking for current progress

/**
 * Attempts to change the goals of the user.
 * Captures and sanitises the posted data.
 * If all fields have been successfully posted, checks they meet the validation checks. 
 * Checks the values have been changes, so there is at least one change, and that they are numeric.
 * If it passes all checks, submits the change to the goals.
 */

if (isset($_POST['goalSubmit'])) {
  $updateGWeight = $_POST['gWeight'];
  $sanitisedUpdateGWeight = $conn->real_escape_string(trim($updateGWeight));
  $updateGBMI = $_POST['gBMI'];
  $sanitisedUpdateGBMI = $conn->real_escape_string(trim($updateGBMI));
  $updateGBFat = $_POST['gBFat'];
  $sanitisedUpdateGBFat = $conn->real_escape_string(trim($updateGBFat));
  $minimumBFGoal = 5.0;
  $maximumBFGoal = 55.0;

  $updateGoals = "UPDATE webdev_user_stats
  SET webdev_user_stats.weight_goal = '$sanitisedUpdateGWeight',webdev_user_stats.BMI_goal = '$sanitisedUpdateGBMI', 
  webdev_user_stats.body_fat_goal = '$sanitisedUpdateGBFat'
  WHERE webdev_user_stats.user_id = '$userid'";

  /**
   * Determines all fields have been changed. If all the same, does not send query and outputs error message.
   * If height, weight, bmi or body fat values are not numeric it displays an error and does not send query.
   * Else, if all is okay it sends the query and a success message is sent.
   */

  if (($goalWeight == $updateGWeight) && ($goalBMI == $updateGBMI)
    && ($goalBFat == $updateGBFat)
  ) {
    $updateFailed = "Your details have not been updated - you have not changed any fields.";
  } else if (!is_numeric($updateGWeight)) {
    $updateFailed = "Your details have not been updated - goal weight must be numeric.";
  } else if (!is_numeric($updateGBMI)) {
    $updateFailed = "Your details have not been updated - goal BMI must be numeric.";
  } else if (!is_numeric($updateGBFat)) {
    $updateFailed = "Your details have not been updated - goal body fat % must be numeric.";
  } else if ($sanitisedUpdateGBFat < $minimumBFGoal || $sanitisedUpdateGBFat > $maximumBFGoal) {
    $updateFailed = "Your details have not been updated - goal body fat must be a value between 1-55.";
  } else {
    $executeUpdateGoal = $conn->query($updateGoals);


    if (!$executeUpdateGoal) {
      echo $conn->error;
    } else {
      $updateSuccessful = "Your details have successfully been updated.
        
";
    }
  }
} // end of checking for goal post

/**
 * Attempts to change the password of the user.
 * Captures and sanitises the posted data.
 * If both fields have been successfully posted, checks they meet the validation checks. 
 * Will also check that the current password entered equals the one on file. 
 * If it passes all checks, submits the change to the new password.
 */
if (isset($_POST['newPasswordSubmit'])) {
  $confirmCurrent = $_POST['currentPassword'];
  $sanitisedConfirmCurrent = $conn->real_escape_string(trim($confirmCurrent));
  $updatedPassword = $_POST['newPass'];
  $sanitisedUpdatedPassword = $conn->real_escape_string(trim($updatedPassword));
  $confirmUpdatedPass = $_POST['confirmNewPass'];
  $sanitisedConfirmUpdatedPass = $conn->real_escape_string(trim($confirmUpdatedPass));
  // grab password stored in database, decrypt it
  $grabCurrentPass = $conn->prepare("SELECT AES_DECRYPT(password, '09UYO2ELHJ290OYEH22098H9ty') AS password from webdev_users 
  WHERE id = ?");
  $grabCurrentPass->bind_param("i", $userid);
  $grabCurrentPass->execute();
  $grabCurrentPass->store_result();
  $grabCurrentPass->bind_result($currentPass);
  $grabCurrentPass->fetch();


  /**
   * Determines password has been changed. If all the same, does not send query and outputs error message.
   * If new password is different from old but if confirmed password is not the same as initial new password, 
   * displays error and no query is sent.
   * Else, if all is okay it sends the query and a success message is sent.
   *  
   * Regex for password check from online guide
   * https://stackoverflow.com/questions/42467243/regex-strong-password-the-special-characters
   *
   */
  if ($updatedPassword != $confirmUpdatedPass) {
    $updateFailed = "Your password has not been changed - confirm different from new password.";
  } else if (($updatedPassword ==  $currentPass) && ($confirmUpdatedPass == $currentPass)) {
    $updateFailed = "Your password has not been changed - same as current.";
  } else if ($confirmCurrent !=  $currentPass) {
    $updateFailed = "Your password has not been changed - current password incorrect.";
  } else if (!preg_match("/\d/", $confirmUpdatedPass)) {
    $updateFailed = "Your password has not been changed -  password should contain one digit at least.";
  }
  if (!preg_match("/[A-Z]/", $confirmUpdatedPass)) {
    $updateFailed = "Your password has not been changed -  password should contain at least one uppercase Letter";
  }
  if (!preg_match("/[a-z]/", $confirmUpdatedPass)) {
    $updateFailed = "Your password has not been changed -  password must contain at least one lowercase letter.";
  }
  if (!preg_match("/\W/", $confirmUpdatedPass)) {
    $updateFailed = "Your password has not been changed -  password should contain at least one special character.";
  } else {

    $changePassword = "UPDATE webdev_users
  SET webdev_users.password = AES_ENCRYPT('$sanitisedConfirmUpdatedPass', '09UYO2ELHJ290OYEH22098H9ty')
  WHERE webdev_users.id = '$userid'";
    $executeChangePass = $conn->query($changePassword);

    if (!$executeChangePass) {
      echo $conn->error;
    }
    $updateSuccessful = "Your password has been changed.";
  }
}

if (isset($_POST['regimeSubmit'])) {
  $newDietPlan = $_POST['dietPlan'];
  $sanitisedDietPlan = $conn->real_escape_string(trim($newDietPlan));
  $newMondayPlan = $_POST['mondayPlan'];
  $sanitisedMondayPlan = $conn->real_escape_string(trim($newMondayPlan));
  $newTuesdayPlan = $_POST['tuesdayPlan'];
  $sanitisedTuesdayPlan = $conn->real_escape_string(trim($newTuesdayPlan));
  $newWednesdayPlan = $_POST['wednesdayPlan'];
  $sanitisedWednesdayPlan = $conn->real_escape_string(trim($newWednesdayPlan));
  $newThursdayPlan = $_POST['thursdayPlan'];
  $sanitisedThursdayPlan = $conn->real_escape_string(trim($newThursdayPlan));
  $newFridayPlan = $_POST['fridayPlan'];
  $sanitisedFridayPlan = $conn->real_escape_string(trim($newFridayPlan));
  $newSaturdayPlan = $_POST['saturdayPlan'];
  $sanitisedSaturdayPlan  = $conn->real_escape_string(trim($newSaturdayPlan));
  $newSundayPlan = $_POST['sundayPlan'];
  $sanitisedSundayPlan = $conn->real_escape_string(trim($newSundayPlan));

  if (($newDietPlan == $currentDiet) && ($newMondayPlan == $currentMonday)
    &&  ($newTuesdayPlan == $currentTuesday) && ($newWednesdayPlan == $currentWednesday) &&
    ($newThursdayPlan == $currentThursday) &&
    ($newFridayPlan == $currentFriday) &&
    ($newSaturdayPlan == $currentSatuday)  && ($newSundayPlan == $currentSunday)
  ) {
    $updateFailed = "Your regime has not been updated - you have not changed any fields.";
  } else {
    $updatePlan = "UPDATE webdev_training_regime
SET webdev_training_regime.diet_plan = $sanitisedDietPlan, webdev_training_regime.monday = $sanitisedMondayPlan,
webdev_training_regime.tuesday = $sanitisedTuesdayPlan, webdev_training_regime.wednesday = $sanitisedWednesdayPlan,
webdev_training_regime.thursday = $sanitisedThursdayPlan, webdev_training_regime.friday = $sanitisedFridayPlan,
webdev_training_regime.saturday = $sanitisedSaturdayPlan, webdev_training_regime.sunday = $sanitisedSundayPlan
WHERE user_id = $userid";

    $executeUpdatePlan = $conn->query($updatePlan);
    if (!$executeUpdatePlan) {
      echo $conn->error;
    }
    $updateSuccessful = "Your regime has been changed.";
  }
}


if (isset($_POST['testimSubmit'])) {
  $testimonialTitle = $_POST['testimonialTitle'];
  $sanitisedTestimonialTitle = $conn->real_escape_string(trim($testimonialTitle));
  $testimonialTextBody = $_POST['testimonialTextBody'];
  $sanitisedTestimonialTextBody = $conn->real_escape_string(trim($testimonialTextBody));
  $doesTestimExist = $_POST['doesTestimExist'];
  if ($doesTestimExist == 0) {
    $getCoachOfUser = $conn->prepare("SELECT coach FROM webdev_user_details WHERE user_id = ?");
    $getCoachOfUser->bind_param("i", $userid);
    $getCoachOfUser->execute();
    $getCoachOfUser->store_result();
    $getCoachOfUser->bind_result($coachID);
    $getCoachOfUser->fetch();
    $sendTestimonial = "INSERT INTO webdev_testimonials (user_id, coach_id, testimonial, title) 
    VALUES ('$userid', '$coachID', '$sanitisedTestimonialTextBody', '$sanitisedTestimonialTitle')";
  } else if ($doesTestimExist == 1) {
    $sendTestimonial = "UPDATE webdev_testimonials
    SET testimonial = '$sanitisedTestimonialTextBody', title = '$sanitisedTestimonialTitle'
    WHERE user_id = $userid";
  }
  $executeSendTestimonial = $conn->query($sendTestimonial);
  if (!$executeSendTestimonial) {
    echo $conn->error;
    $updateFailed = "Testimony could not be updated";
  }
  $updateSuccessful = "Testimonial successfully updated";
}

if (isset($_POST['deleteAccountButton'])) {

  $delCurrentPassword = $_POST['delCurrentPassword'];
  $sanitisedDelCurrentPassword  = $conn->real_escape_string(trim($delCurrentPassword));
  $delConfirmPassword = $_POST['delConfirmPassword'];
  $sanitisedDelConfirmPassword = $conn->real_escape_string(trim($delConfirmPassword));

  // grab password stored in database, decrypt it
  $grabCurrentPass = $conn->prepare("SELECT AES_DECRYPT(password, '09UYO2ELHJ290OYEH22098H9ty') AS password from webdev_users 
    WHERE id = ?");
  $grabCurrentPass->bind_param("i", $userid);
  $grabCurrentPass->execute();
  $grabCurrentPass->store_result();
  $grabCurrentPass->bind_result($currentPass);
  $grabCurrentPass->fetch();

  //get user's email to email them if successful.
  $grabEmail = $conn->prepare("SELECT email from webdev_users   WHERE id = ?");
  $grabEmail->bind_param("i", $userid);
  $grabEmail->execute();
  $grabEmail->store_result();
  $grabEmail->bind_result($userEmail);
  $grabEmail->fetch();

  if (($sanitisedDelCurrentPassword == $currentPass) && ($sanitisedDelConfirmPassword == $currentPass)) {
    /**
     * transaction adapted from online tutorial <https://www.youtube.com/watch?v=CNt9HPqDIVc>
     * 
     * This transaction deleted all entries within the database which contain the user who is being deleted.
     * As there are foreign key constraints, cannot just delete the user - must delete all of their relevant data,
     * such as inbox, stats, etc before actually deleting the user from the table. 
     * This will free up the username to be taken again. 
     */
    $conn->autocommit(false);

    $deleteError = array();

    $a = $conn->query("DELETE FROM webdev_appointments WHERE user_id = '$userid'");
    if ($a == false) {
      array_push($deleteError, 'Problem deleting appointments from db');
      echo $conn->error;
    }
    $b = $conn->query("UPDATE webdev_groups SET member_one = '0' WHERE member_one = '$userid'");
    if ($b == false) {
      array_push($deleteError, 'Problem removing user as member of group.');
      echo $conn->error;
    }

    $c = $conn->query("UPDATE webdev_groups SET member_two = '0' WHERE member_two = '$userid'");
    if ($c == false) {
      array_push($deleteError, 'Problem removing user as member of group.');
      echo $conn->error;
    }


    $d = $conn->query("UPDATE webdev_groups SET member_three = '0' WHERE member_three = '$userid'");
    if ($d == false) {
      array_push($deleteError, 'Problem removing user as member of group.');
      echo $conn->error;
    }


    $e = $conn->query("UPDATE webdev_groups SET member_four = '0' WHERE member_four = '$userid'");
    if ($e == false) {
      array_push($deleteError, 'Problem removing user as member of group.');
      echo $conn->error;
    }


    $f = $conn->query("DELETE FROM webdev_inbox WHERE recipient = '$userid'");
    if ($f == false) {
      array_push($deleteError, 'Problem deleting inbox from db');
      echo $conn->error;
    }


    $g = $conn->query("DELETE FROM webdev_training_regime WHERE user_id = '$userid'");
    if ($g == false) {
      array_push($deleteError, 'Problem deleting regime from db');
      echo $conn->error;
    }

    $h = $conn->query("DELETE FROM webdev_user_details WHERE user_id = '$userid'");
    if ($h == false) {
      array_push($deleteError, 'Problem deleting details from db');
      echo $conn->error;
    }

    $i = $conn->query("DELETE FROM webdev_user_stats WHERE user_id = '$userid'");
    if ($i == false) {
      array_push($deleteError, 'Problem deleting user stats from db');
      echo $conn->error;
    }

    $j = $conn->query("DELETE FROM webdev_inbox WHERE sender = '$userid'");
    if ($j == false) {
      array_push($deleteError, 'Problem deleting inbox from db');
      echo $conn->error;
    }

    $k = $conn->query("DELETE FROM webdev_testimonials WHERE user_id = '$userid'");
    if ($k == false) {
      array_push($deleteError, 'Problem deleting inbox from db');
      echo $conn->error;
    }

    $l = $conn->query("DELETE FROM webdev_users WHERE id = '$userid'");
    if ($l == false) {
      array_push($deleteError, 'Problem deleting user from db');
      echo $conn->error;
    }


    /**
     * If array error not empty, error occured and rollback occurs.
     */
    if (!empty($deleteError)) {
      foreach ($deleteError as $thing) {
        echo $thing;
      }
      $conn->rollback();
    } else {

      //commit if all ok
      $conn->commit();
      // message user to confirm acc deletion
      $message = "Dear user, \n This is an automated message, please do not reply. 
      \n This is an email to confirm that your account has been deleted. We are sorry to see you go. 
      \n You are welcome to sign up again at any time. We hope to see you again. 
      \n Kind regards,
      \n Gymafi.";
      mail($userEmail, 'Gymafi - Account Deletion', $message);
      header("location: logout.php");
    }
  }
}
?>

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Gymafi | Profile</title>
  <link href="styles/bulma.css" rel="stylesheet">
  <link href="styles/gui.css" rel="stylesheet">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script src="script/myScript.js"></script>

</head>

<body class="has-background-grey-lighter">
  <?php
  echo " 
    <nav class='navbar is-dark' role='navigation' aria-label='main navigation'>
<div class='navbar-end'>
      <div class='navbar-item'>
      <div class='buttons'>
      <a class='button is-primary' href='profile.php'>
         Profile
        </a>
        <a class='button is-danger' href='logout.php'>
           Logout
          </a>
        </div>
        </div>
      </div>
    </div>
</nav>";

  ?>

  <section class="hero is-dark is-small">
    <div class="hero-body">
      <div class="container">
        <h1 class="title myTitle">
          Gymafi
        </h1>
        <h2 class="subtitle myTitle">
          Unlocking Your Potential
        </h2>
      </div>
    </div>
  </section>

  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">


    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu has-background-dark">
      <div class="navbar-start myNav">
        <a class="navbar-item has-text-white" href='dashboard.php'>
          Dashboard
        </a>

        <a class='navbar-item has-background-dark has-text-white' href='appointments.php'>
          Appointments
        </a>

        <a class="navbar-item has-background-dark has-text-white" href='inbox.php'>
          Inbox
        </a>
        <a class='navbar-item has-background-dark has-text-white' href='performance.php'>
          Performance Log
        </a>
        <a class="navbar-item has-text-white" href='gallery.php'>
          Your Gallery
        </a>

      </div> <!-- end of navbarBasicExample-->


    </div>
  </nav>




  <?php

  /**
   * If user's account has not been approved by their desired coach, displays an error image/message and does not show the 
   * webpage as an approved use would see. 
   * User can click on the button to return to the dashboard.
   */

  $checkIfApproved = $conn->prepare("SELECT approved FROM webdev_users WHERE id = ?");
  $checkIfApproved->bind_param("i", $userid);
  $checkIfApproved->execute();
  $checkIfApproved->store_result();
  $checkIfApproved->bind_result($isApproved);
  $checkIfApproved->fetch();


  if ($isApproved == 1) {

  ?>
    <div class='container' id='myProfile'>
      <div class='notification'>
        <nav class='level'>
          <!-- Left side -->
          <div class='level-left leftProfileHeadStuff'>
            <div class='level-item'>
              <h1 class='title' id='refreshName'>
                <?php
                echo htmlentities($userActualName, ENT_QUOTES);
                ?>
              </h1>

            </div>

          </div>

          <!-- Right side -->
          <div class='level-right'>
            <h1 class='title'><a id='syncDetails'><span class='icon is-large'>
                  <i class='fas fa-sync'></i>
                </span></h1></a>


          </div>
        </nav>

        <nav class='level'>
          <!-- Left side -->

          <div class='level-left'>


          </div>



          <!-- Right side -->
          <!-- Right side -->
          <div class='level-right RightProfileHeadStuff'>
            <div class='level-item '>
              <?php
              echo "
              <img src='images/uploaded/$userPicture' id='profilePic'>";
              ?>
            </div>


          </div>

        </nav>

        <div id='packageInfo'>
          <div class='columns'>

            <div class='column'>
              <article class='message is-link profileBox' id='refreshFirstCol'>
                <div class='message-header'>
                  Personal Details <span class='icon is-small'>
                    <i class='fas fa-user-shield'></i>
                  </span>

                </div>
                <div class='message-body'>
                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff '>
                      <div class='level-item'>
                        <?php
                        echo "
                        <p class='level-item'><strong>
                            <p>Username: ", htmlentities($username, ENT_QUOTES);
                        ?>
                        </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>


                    </div>

                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <?php
                        echo "
                        <p class='level-item'><strong>
                            <p>Age: $age (", htmlentities($dateOfBirth, ENT_QUOTES), ")";
                        ?>
                        </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>


                    </div>

                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Phone Number:  ", htmlentities($userPhoneNumber, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>


                    </div>
                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Email Address: ", htmlentities($userEmail, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>
                      <p class='level-item'>

                    </div>
                  </nav>

                  <nav class='level '>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Address: ", htmlentities($userAddress, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>


                    </div>
                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p> ", htmlentities($userCity, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>


                    </div>
                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>", htmlentities($userPostcode, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>

                    </div>
                  </nav>

                </div> <!-- end of message body-->
              </article>

            </div><!-- end of column-->


            <div class='column'>
              <article class='message is-link profileBox' id='refreshSecondCol'>
                <div class='message-header'>
                  Current Progress
                  <span class='icon is-small'>
                    <i class='far fa-clipboard'></i>
                  </span>



                </div>
                <div class='message-body'>


                  <nav class='level '>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Height (cm): ", htmlentities($height, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>


                    </div>
                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Starting Weight: ", htmlentities($startingWeight, ENT_QUOTES), " kg";
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>


                    </div>
                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Weight: ", htmlentities($currentWeight, ENT_QUOTES), " kg";
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>


                    </div>
                  </nav>


                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Total Weight Loss: ", htmlentities($weightLost, ENT_QUOTES), " kg";
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>

                    </div>
                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>BMI: ", htmlentities($currentBMI, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>

                    </div>
                  </nav>

                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Body fat: ", htmlentities($currentBFat, ENT_QUOTES), " %";
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>
                    <!-- Right side -->
                    <div class='level-right'>

                    </div>
                  </nav>

                </div> <!-- end of message body-->
              </article>
            </div><!-- end of column-->

            <div class='column'>
              <article class='message is-link profileBox' id='refreshThirdCol'>
                <div class='message-header'>
                  Goals
                  <span class='icon is-small'>
                    <i class='fas fa-bullseye'></i>
                  </span>

                </div>
                <div class='message-body'>
                  <nav class='level'>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Weight:  ", htmlentities($goalWeight, ENT_QUOTES),  " kg";
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>

                    </div>

                  </nav>

                  <nav class='level '>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>BMI:  ", htmlentities($goalBMI, ENT_QUOTES);
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>

                    </div>
                  </nav>

                  <nav class='level '>
                    <!-- Left side -->
                    <div class='level-left leftProfileStuff'>
                      <div class='level-item'>
                        <p class='level-item'><strong>
                            <?php
                            echo "
                            <p>Body fat: ", htmlentities($goalBFat, ENT_QUOTES), "%";
                            ?>
                          </strong></p>
                        </p>
                      </div>

                    </div>

                    <!-- Right side -->
                    <div class='level-right'>


                    </div>
                  </nav>

                </div> <!-- end of message body-->
              </article>

            </div><!-- end of column-->

          </div> <!-- end of columns-->

        </div><!-- end of package info-->

        <nav class='level'>
          <!-- Left side -->
          <div class='level-left leftProfileStuff' id='profileSettings'>
            <div class='level-item '>
              <?php
              if (isset($updateFailed)) {
                echo "<p id='failedUpdate'>$updateFailed</p>";
              } else if (isset($updateSuccessful)) {
                echo "<p id='successfulUpdate'>$updateSuccessful</p>";
              }
              ?>
            </div>

          </div>

          <!-- Right side -->
          <div class='level-right'>
            <div class='level-item' id='profileButtons'>
              <a class='button is-danger is-medium' id='changePassword'>
                Change Password

              </a></span>
              &nbsp;
              <a class='button is-success is-medium' id='updatePersonal'>
                Update Details

              </a>

            </div>

          </div>

        </nav>

      </div>
    </div> "
    <!--end of container-->



    <!-- modal for changing personal details-->

    <div class='modal' id='editPersonalDetails'>
      <div class='modal-background '></div>
      <div class='modal-card'>
        <header class='modal-card-head'>
          <p class='modal-card-title'>Update Personal Details</p>
          <button class='delete cancelUpdate' aria-label='close'></button>

        </header>

        <section class='modal-card-body'>
          <div class='field is-grouped is-grouped-multiline' id='modalSelectionButtons'>

            <p class='control'>
              <button class='button'>
                Personal Details   <span class='icon is-small'>
                  <i class='fas fa-user-shield'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button updateCurrentProgressButton'>
                Current Progress  <span class='icon is-small'>
                  <i class='far fa-clipboard'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button updateGoalsButton'>
                Goals   <span class='icon is-small'>
                  <i class='fas fa-bullseye'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button updateRegimeButton'>
                Training Regime   <span class='icon is-small'>
                  <i class='fas fa-dumbbell'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button updatePassword'>
                Password  <span class='icon is-small'>
                  <i class='fas fa-key'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button updateTestimonial'>
                Testimonial   <span class='icon is-small'>
                  <i class='fas fa-star-half-alt'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button delAccount'>
                Delete Account  <span class='icon is-small'>
                  <i class='fas fa-user-slash'></i>
                </span>
              </button>
            </p>
          </div>

          <form action='profile.php' method='POST' id='changeDetailsForm'>
            <div class='field'>
              <label class='label'>Username</label>
              <div class='control'>
                <input class='input' id='usernameChange' type='text' value="<?php echo $username ?>" name='newUsername'>
              </div>
              <p class='help is-danger' id='usernameChangeWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Your Name: </label>
              <div class='control'>
                <input class='input' id='realNameChange' type='text' value="<?php echo $userActualName ?>" name='newName'>
              </div>
              <p class='help is-danger' id='realNameChangeWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Date of birth(YYYY-MM-DD): </label>
              <div class='control'>
                <input class='input' type='date' id='datepicker dateChange' value="<?php echo $dateOfBirth ?>" name='updateDOB'>
              </div>
              <p class='help is-danger' id='dateChangeWarn'> </p>
            </div>




            <div class='field'>
              <label class='label'>Email address: </label>
              <div class='control'>
                <input class='input' type='email' id='emailChange' value="<?php echo $userEmail ?>" name='newEmail'>
              </div>
              <p class='help is-danger' id='emailChangeWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Telephone Number: </label>
              <div class='control'>
                <input class='input' type='text' id='phoneChange' value="<?php echo $userPhoneNumber ?>" name='newNumber'>
              </div>
              <p class='help is-danger' id='phoneChangeWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Address: </label>
              <div class='control'>
                <input class='input' type='text' id='addressChange' value="<?php echo $userAddress ?>" name='newAddressOne'>
              </div>
              <p class='help is-danger' id='addressChangeWarn'> </p>
            </div>



            <div class='field'>
              <label class='label'>City: </label>
              <div class='control'>
                <input class='input' type='text' id='cityChange' value="<?php echo $userCity ?>" name='newCity'>
              </div>
              <p class='help is-danger' id='cityChangeWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Postcode: </label>
              <div class='control'>
                <input class='input' type='text' id='postcodeChange' value="<?php echo $userPostcode ?>" name='newPostcode'>
              </div>
              <p class='help is-danger' id='postcodeChangeWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Change your profile photo: </label>
              <div class='control select'>
                <select name='changePic'>
                  <?php
                  $getPics = "SELECT webdev_images.path, webdev_images.description, webdev_user_details.picture
                  FROM webdev_images
                  INNER JOIN webdev_user_details
                  ON webdev_images.user_id = webdev_user_details.user_id
                  WHERE webdev_images.user_id= $userid
                  ORDER BY webdev_images.description ASC;";
                  $executeGetPics = $conn->query($getPics);
                  if (!$executeGetPics) {
                    echo $conn->error;
                  }
                  while ($row = $executeGetPics->fetch_assoc()) {

                    $picPath = $row['path'];
                    $imgDesc = $row['description'];
                    $currentPic = $row['picture'];

                    if ($picPath == $currentPic) {
                      echo "<option selected value='$picPath'> $imgDesc ($picPath)</option>";
                    } else {
                      echo "<option value='$picPath'> $imgDesc ($picPath)</option>";
                    }
                  }
                  ?>
                </select>
              </div>
            </div>
            <footer class='modal-card-foot'>
              <p class='control'>
                <input type='submit' class='button is-success detailsIfValid' id='detailsSubmit' value='Save changes' name='detailsSubmit'>
                <button class='button cancelUpdate'>Cancel</button>
            </footer>
          </form>
        </section>

      </div>
    </div>


    <!-- modal for editing current progress -->

    <div class='modal ' id='editCurrentProgress'>
      <div class='modal-background '></div>
      <div class='modal-card'>
        <header class='modal-card-head'>
          <p class='modal-card-title'>Update Current Progress</p>
          <button class='delete cancelUpdate' aria-label='close' id='cancelUpdateCurrentProgressButton'></button>

        </header>

        <section class='modal-card-body'>
          <div class='field is-grouped is-grouped-multiline' id='modalSelectionButtons'>
            <p class='control'>
              <button class='button updatePersonalDetailsButton'>
                Personal Details   <span class='icon is-small'>
                  <i class='fas fa-user-shield'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button'>
                Current Progress  <span class='icon is-small'>
                  <i class='far fa-clipboard'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateGoalsButton'>
                Goals   <span class='icon is-small'>
                  <i class='fas fa-bullseye'></i>
                </span>
              </button>
              <p class='control'>
                <button class='button updateRegimeButton'>
                  Training Regime   <span class='icon is-small'>
                    <i class='fas fa-dumbbell'></i>
                  </span>
                </button>
              </p>
            </p>
            <p class='control'>
              <button class='button updatePassword'>
                Password  <span class='icon is-small'>
                  <i class='fas fa-key'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateTestimonial'>
                Testimonial    <span class='icon is-small'>
                  <i class='fas fa-star-half-alt'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button delAccount'>
                Delete Account  <span class='icon is-small'>
                  <i class='fas fa-user-slash'></i>
                </span>
              </button>
            </p>
          </div>
          <form action='profile.php' method='POST' id='currentProgressForm'>


            <div class='field'>
              <label class='label'>Height(cm): </label>
              <div class='control'>
                <input class='input' id='height' type='number' step='0.1' min='140' max='213' value="<?php echo $height ?>" name='height'>
              </div>
              <p class='help is-danger' id='heightWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Starting weight(kg): </label>
              <div class='control'>
                <input class='input' id='startingWeight' type='number' step='0.1' min='30' max='250' value="<?php echo $startingWeight ?>" name='sWeight'>
              </div>
              <p class='help is-danger' id='startingWeightWarn'> </p>
            </div>


            <div class='field'>
              <label class='label'>Current weight(kg): </label>
              <div class='control'>
                <input class='input' id='currentWeight' type='number' step='0.1' min='40' max='250' value="<?php echo $currentWeight ?>" name='cWeight'>
              </div>
              <p class='help is-danger' id='currentWeightWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>BMI </label>
              <div class='control'>
                <input class='input' id='currentBMI' type='number' step='0.1' min='10.0' max='60.0' value="<?php echo $currentBMI ?>" name='cBMI'>
              </div>
              <p class='help is-danger' id='currentBMIWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Body fat: </label>
              <div class='control'>
                <input class='input' id='currentBodyFat' type='number' step='0.1' min='1.0' max='60.0' value="<?php echo $currentBFat ?>" name='cBFat'>
              </div>
              <p class='help is-danger' id='currentBodyFatWarn'> </p>
            </div>

            <footer class='modal-card-foot'>
              <input type='submit' class='button is-success currentValsIfValid' id='progressSubmit' value='Save changes' name='progressSubmit'>
              <button class='button cancelUpdate'>Cancel</button>
            </footer>

          </form>
        </section>

      </div>
    </div>


    <!-- modal for editing goals -->
    <div class='modal ' id='editGoals'>
      <div class='modal-background '></div>
      <div class='modal-card'>
        <header class='modal-card-head'>
          <p class='modal-card-title'>Update Goals</p>
          <button class='delete cancelUpdate' aria-label='close'></button>

        </header>

        <section class='modal-card-body'>
          <div class='field is-grouped is-grouped-multiline' id='modalSelectionButtons'>
            <p class='control'>
              <button class='button updatePersonalDetailsButton'>
                Personal Details   <span class='icon is-small'>
                  <i class='fas fa-user-shield'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateCurrentProgressButton'>
                Current Progress  <span class='icon is-small'>
                  <i class='far fa-clipboard'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button'>
                Goals   <span class='icon is-small'>
                  <i class='fas fa-bullseye'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateRegimeButton'>
                Training Regime   <span class='icon is-small'>
                  <i class='fas fa-dumbbell'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updatePassword'>
                Password  <span class='icon is-small'>
                  <i class='fas fa-key'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateTestimonial'>
                Testimonial   <span class='icon is-small'>
                  <i class='fas fa-star-half-alt'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button delAccount'>
                Delete Account  <span class='icon is-small'>
                  <i class='fas fa-user-slash'></i>
                </span>
              </button>
            </p>
          </div>

          <form action='profile.php' method='POST' id='goalsForm'>
            <div class='field'>
              <label class='label'>Weight(kg): </label>
              <div class='control'>
                <input class='input' id='goalWeight' type='text' value="<?php echo $goalWeight ?>" name='gWeight'>
              </div>
              <p class='help is-danger' id='goalWeightWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>BMI </label>
              <div class='control'>
                <input class='input' id='goalBMI' type='text' step='0.1' min='15.0' max='40.0' value="<?php echo $goalBMI ?>" name='gBMI'>
              </div>
              <p class='help is-danger' id='goalBMIWarn'> </p>
            </div>
            <div class='field'>
              <label class='label'>Body Fat: </label>
              <div class='control'>
                <input class='input' id='goalBodyFat' type='text' step='0.1' min='5.0' max='35.0' value="<?php echo $goalBFat ?>" name='gBFat'>
              </div>
              <p class='help is-danger' id='goalBodyFatWarn'> </p>
            </div>


            <footer class='modal-card-foot'>
              <input type='submit' class='button is-success goalsIfValid' id='goalSubmit' value='Save changes' name='goalSubmit'>
              <button class='button cancelUpdate'>Cancel</button>
            </footer>


          </form>
        </section>

      </div>
    </div>




    <!-- modal for editing training regime -->

    <div class='modal' id='editRegime'>
      <div class='modal-background '></div>
      <div class='modal-card'>
        <header class='modal-card-head'>
          <p class='modal-card-title'>Update Regime</p>
          <button class='delete cancelUpdate' aria-label='close'></button>

        </header>

        <section class='modal-card-body'>
          <div class='field is-grouped is-grouped-multiline' id='modalSelectionButtons'>
            <p class='control'>
              <button class='button updatePersonalDetailsButton'>
                Personal Details   <span class='icon is-small'>
                  <i class='fas fa-user-shield'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateCurrentProgressButton'>
                Current Progress  <span class='icon is-small'>
                  <i class='far fa-clipboard'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateGoalsButton'>
                Goals   <span class='icon is-small'>
                  <i class='fas fa-bullseye'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button'>
                Training Regime   <span class='icon is-small'>
                  <i class='fas fa-dumbbell'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updatePassword'>
                Password  <span class='icon is-small'>
                  <i class='fas fa-key'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateTestimonial'>
                Testimonial    <span class='icon is-small'>
                  <i class='fas fa-star-half-alt'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button delAccount'>
                Delete Account  <span class='icon is-small'>
                  <i class='fas fa-user-slash'></i>
                </span>
              </button>
            </p>
          </div>
          <?php
          echo "
      <form action='profile.php' method='POST'>
        <div class='field'>
          <label class='label'>Diet plan: </label>
          
          <div class='control select'>
          <select name='dietPlan'> 
          ";

          $getAllDietPlans = "SELECT * FROM webdev_training_meals";
          $executeGetAllDietPlans = $conn->query($getAllDietPlans);
          if (!$executeGetAllDietPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetAllDietPlans->fetch_assoc()) {
            $dietID = $row['id'];
            $dietDesc = $row['meal_type'];
            if ($dietID == $currentDiet) {
              echo "<option selected value='$dietID'>$dietDesc</option>";
            } else {
              echo "<option value='$dietID'>$dietDesc</option>";
            }
          }

          echo "
          </select>
        </div>

        <div class='field'>
        <label class='label'>Monday: </label>
        
        <div class='control select'>
        <select name='mondayPlan'> 
        ";

          $getPlans = "SELECT * FROM webdev_training_plans";
          $executeGetPlans = $conn->query($getPlans);
          if (!$executeGetPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetPlans->fetch_assoc()) {
            $planID = $row['id'];
            $planDesc = $row['plan'];
            if ($planID == $currentMonday) {
              echo "<option selected value='$planID'>$planDesc</option>";
            } else {
              echo "<option value='$planID'>$planDesc</option>";
            }
          }

          echo "
        </select>
      </div>
      
      <div class='field'>
      <label class='label'>Tuesday: </label>
      <div class='control select'>
      <select name='tuesdayPlan'> 
      ";

          $getPlans = "SELECT * FROM webdev_training_plans";
          $executeGetPlans = $conn->query($getPlans);
          if (!$executeGetPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetPlans->fetch_assoc()) {
            $planID = $row['id'];
            $planDesc = $row['plan'];
            if ($planID == $currentTuesday) {
              echo "<option selected value='$planID'>$planDesc</option>";
            } else {
              echo "<option value='$planID'>$planDesc</option>";
            }
          }

          echo "
      </select>
    </div>





      <div class='field'>
      <label class='label'>Wednesday: </label>
      <div class='control select'>
        <select name='wednesdayPlan'> 
        ";

          $getPlans = "SELECT * FROM webdev_training_plans";
          $executeGetPlans = $conn->query($getPlans);
          if (!$executeGetPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetPlans->fetch_assoc()) {
            $planID = $row['id'];
            $planDesc = $row['plan'];
            if ($planID == $currentWednesday) {
              echo "<option selected value='$planID'>$planDesc</option>";
            } else {
              echo "<option value='$planID'>$planDesc</option>";
            }
          }

          echo "
        </select>
      </div>

      <div class='field'>
      <label class='label'>Thursday: </label>
      <div class='control select'>
      <select name='thursdayPlan'> 
      ";

          $getPlans = "SELECT * FROM webdev_training_plans";
          $executeGetPlans = $conn->query($getPlans);
          if (!$executeGetPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetPlans->fetch_assoc()) {
            $planID = $row['id'];
            $planDesc = $row['plan'];
            if ($planID == $currentThursday) {
              echo "<option selected value='$planID'>$planDesc</option>";
            } else {
              echo "<option value='$planID'>$planDesc</option>";
            }
          }

          echo "
      </select>
    </div>




      <div class='field'>
      <label class='label'>Friday: </label>
       <div class='control select'>
        <select name='fridayPlan'> 
        ";

          $getPlans = "SELECT * FROM webdev_training_plans";
          $executeGetPlans = $conn->query($getPlans);
          if (!$executeGetPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetPlans->fetch_assoc()) {
            $planID = $row['id'];
            $planDesc = $row['plan'];
            if ($planID == $currentFriday) {
              echo "<option selected value='$planID'>$planDesc</option>";
            } else {
              echo "<option value='$planID'>$planDesc</option>";
            }
          }

          echo "
        </select>
      </div>


      <div class='field'>
      <label class='label'>Saturday: </label>
      <div class='control select'>
      <select name='saturdayPlan'> 
      ";

          $getPlans = "SELECT * FROM webdev_training_plans";
          $executeGetPlans = $conn->query($getPlans);
          if (!$executeGetPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetPlans->fetch_assoc()) {
            $planID = $row['id'];
            $planDesc = $row['plan'];
            if ($planID == $currentSatuday) {
              echo "<option selected value='$planID'>$planDesc</option>";
            } else {
              echo "<option value='$planID'>$planDesc</option>";
            }
          }

          echo "
      </select>
    </div>




      <div class='field'>
      <label class='label'>Sunday: </label>
      <div class='control select'>
      <select name='sundayPlan'> 
      ";

          $getPlans = "SELECT * FROM webdev_training_plans";
          $executeGetPlans = $conn->query($getPlans);
          if (!$executeGetPlans) {
            echo $conn->error;
          }
          while ($row = $executeGetPlans->fetch_assoc()) {
            $planID = $row['id'];
            $planDesc = $row['plan'];
            if ($planID == $currentSunday) {
              echo "<option selected value='$planID'>$planDesc</option>";
            } else {
              echo "<option value='$planID'>$planDesc</option>";
            }
          }

          echo "
      </select>
    </div>
    </div>
      
      <footer class='modal-card-foot'>
      <input type='submit' class='button is-success' id='regimeSubmit' value='Save changes' name='regimeSubmit'>
      <button class='button cancelUpdate'>Cancel</button>
    </footer>


      </form>";
          ?>
        </section>

      </div>
    </div>




    <!-- modal for changing password-->

    <div class='modal ' id='editPassword'>
      <div class='modal-background '></div>
      <div class='modal-card'>
        <header class='modal-card-head'>
          <p class='modal-card-title'>Change Password</p>

          <button class='delete cancelUpdate' aria-label='close'></button>

        </header>

        <section class='modal-card-body'>
          <div class='field is-grouped is-grouped-multiline' id='modalSelectionButtons'>
            <p class='control'>
              <button class='button updatePersonalDetailsButton'>
                Personal Details   <span class='icon is-small'>
                  <i class='fas fa-user-shield'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateCurrentProgressButton'>
                Current Progress  <span class='icon is-small'>
                  <i class='far fa-clipboard'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateGoalsButton'>
                Goals   <span class='icon is-small'>
                  <i class='fas fa-bullseye'></i>
                </span>
              </button>
              <p class='control'>
                <button class='button updateRegimeButton'>
                  Training Regime   <span class='icon is-small'>
                    <i class='fas fa-dumbbell'></i>
                  </span>
                </button>
              </p>
            </p>
            <p class='control'>
              <button class='button'>
                Password  <span class='icon is-small'>
                  <i class='fas fa-key'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateTestimonial'>
                Testimonial    <span class='icon is-small'>
                  <i class='fas fa-star-half-alt'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button delAccount'>
                Delete Account  <span class='icon is-small'>
                  <i class='fas fa-user-slash'></i>
                </span>
              </button>
            </p>
          </div>

          <form action='profile.php' method='POST' id='changePassForm'>
            <div class='field'>
              <label class='label'>Current password: </label>
              <div class='control'>
                <input class='input' type='password' id='currentPass' name='currentPassword'>
              </div>
              <p class='help is-danger' id='currentPassWarn'> </p>
            </div>

            <div class='field'>

              <label class='label'>New password: </label>

              <p>Password should be between 8-16 characters and contain one of the following: an uppercase and lowercase letter, a number and a special character.</p>
              <div class='control'>
                <input class='input' id='newPass' type='password' name='newPass'>
              </div>
              <p class='help is-danger' id='newPassWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Confirm new password: </label>
              <div class='control'>
                <input class='input' id='confirmNewPass' type='password' name='confirmNewPass'>
              </div>
              <p class='help is-danger' id='confirmNewPassWarn'> </p>
            </div>





            <footer class='modal-card-foot'>
              <p class='control'>
                <input type='submit' class='button is-success passwordIfValid' id='newPasswordSubmit' value='Save changes' name='newPasswordSubmit'>
                <button class='button cancelUpdate'>Cancel</button>
            </footer>
          </form>
        </section>

      </div>
    </div>


    <!-- modal for editing testimonial -->

    <div class='modal ' id='editTestimonial'>
      <div class='modal-background '></div>
      <div class='modal-card'>
        <header class='modal-card-head'>
          <p class='modal-card-title'>Update Testimonial</p>
          <button class='delete cancelUpdate' aria-label='close' id='cancelUpdateTestimonialButton'></button>

        </header>
        <?php
        $getTestimonialInfo = $conn->prepare("SELECT testimonial, title FROM webdev_testimonials
    WHERE user_id = ?");
        $getTestimonialInfo->bind_param("i", $userid);
        $getTestimonialInfo->execute();
        $getTestimonialInfo->store_result();
        $getTestimonialInfo->bind_result($testimonialText, $testimonialTitle);
        $getTestimonialInfo->fetch();
        if ($testimonialText != null && $testimonialTitle != null) {
          $testiExists = 1; // variable to check if testimonial already exists as different db query to write depending on if it does or not
        } else {
          $testiExists = 0;
        }
        ?>


        <section class='modal-card-body'>
          <div class='field is-grouped is-grouped-multiline' id='modalSelectionButtons'>
            <p class='control'>
              <button class='button updatePersonalDetailsButton'>
                Personal Details   <span class='icon is-small'>
                  <i class='fas fa-user-shield'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateCurrentProgressButton'>
                Current Progress  <span class='icon is-small'>
                  <i class='far fa-clipboard'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateGoalsButton'>
                Goals   <span class='icon is-small'>
                  <i class='fas fa-bullseye'></i>
                </span>
              </button>
              <p class='control'>
                <button class='button updateRegimeButton'>
                  Training Regime   <span class='icon is-small'>
                    <i class='fas fa-dumbbell'></i>
                  </span>
                </button>
              </p>
            </p>
            <p class='control'>
              <button class='button updatePassword'>
                Password  <span class='icon is-small'>
                  <i class='fas fa-key'></i>
                </span>
              </button>
            </p>


            <p class='control'>
              <button class='button'>
                Testimonial   <span class='icon is-small'>
                  <i class='fas fa-star-half-alt'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button delAccount'>
                Delete Account  <span class='icon is-small'>
                  <i class='fas fa-user-slash'></i>
                </span>
              </button>
            </p>

          </div>
          <form action='profile.php' method='POST' id='updateTestimonialForm'>
            <input type='hidden' id='doesTestimExist' name='doesTestimExist' value="<?php echo $testiExists ?>">
            <div class='field'>
              <label class='label'>Testimonial Title: </label>
              <div class='control'>
                <?php
                /**
                 * If the variable is set, testimonial already exists and sets value to be that of what is brought from database.
                 * Otherwise, displays empty input with placeholder text.
                 */
                if (isset($testimonialTitle)) {
                ?> <input class='input' id='testimonialTitle' value="<?php echo $testimonialTitle ?>" name='testimonialTitle'>
                <?php
                } else {
                  echo "<input class='input' id='testimonialTitle' placeholder='Amazing coach!' name='testimonialTitle'>";
                }
                ?>
              </div>
              <p class='help is-danger' id='testiTitleWarn'> </p>
            </div>

            <div class='field'>
              <label class='label'>Testimonial Text: </label>
              <div class='control'>

                <?php
                /** 
                 * If the variable is set, testimonial already exists and sets value to be that of what is brought from database.
                 * Otherwise, displays empty input with placeholder text.
                 */
                if (isset($testimonialText)) {
                ?>
                  <input class='input' id='testimonialTextBody' type='text' value="<?php echo $testimonialText ?>" name='testimonialTextBody'>
                <?php
                } else {
                  echo " <input class='input' id='testimonialTextBody' type='text' placeholder='Really helpful service, helped me lose 10kg in a month!' name='testimonialTextBody'>";
                }
                ?>
              </div>
              <p class='help is-danger' id='testiTextWarn'> </p>
            </div>

            <footer class='modal-card-foot'>
              <input type='submit' class='button is-success currentTestiIfValid' id='testimSubmit' value='Update Testimonial' name='testimSubmit'>
              <button class='button cancelUpdate'>Cancel</button>
            </footer>

          </form>
        </section>

      </div>
    </div>


    <!-- modal for deleting account-->

    <div class='modal ' id='deleteAcc'>
      <div class='modal-background '></div>
      <div class='modal-card'>
        <header class='modal-card-head'>
          <p class='modal-card-title'>Delete Account</p>

          <button class='delete cancelUpdate' aria-label='close'></button>

        </header>

        <section class='modal-card-body'>
          <div class='field is-grouped is-grouped-multiline' id='modalSelectionButtons'>
            <p class='control'>
              <button class='button updatePersonalDetailsButton'>
                Personal Details   <span class='icon is-small'>
                  <i class='fas fa-user-shield'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateCurrentProgressButton'>
                Current Progress  <span class='icon is-small'>
                  <i class='far fa-clipboard'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateGoalsButton'>
                Goals   <span class='icon is-small'>
                  <i class='fas fa-bullseye'></i>
                </span>
              </button>
              <p class='control'>
                <button class='button updateRegimeButton'>
                  Training Regime   <span class='icon is-small'>
                    <i class='fas fa-dumbbell'></i>
                  </span>
                </button>
              </p>
            </p>
            <p class='control'>
              <button class='button updatePassword'>
                Password  <span class='icon is-small'>
                  <i class='fas fa-key'></i>
                </span>
              </button>
            </p>
            <p class='control'>
              <button class='button updateTestimonial'>
                Testimonial    <span class='icon is-small'>
                  <i class='fas fa-star-half-alt'></i>
                </span>
              </button>
            </p>

            <p class='control'>
              <button class='button'>
                Delete Account  <span class='icon is-small'>
                  <i class='fas fa-user-slash'></i>
                </span>
              </button>
            </p>
          </div>

          <form action='profile.php' method='POST' id='deleteAccountForm'>
            <p> Please note that deleting your account is final - it CANNOT be undone. </p>
            <div class='field'>
              <label class='label'>Enter password: </label>
              <div class='control'>
                <input class='input' type='password' id='delCurrentPassword' name='delCurrentPassword'>
              </div>
              <p class='help is-danger' id='delCurrentPasswordWarn'> </p>
            </div>

            <div class='field'>

              <label class='label'>Confirm password: </label>

              <div class='control'>
                <input class='input' id='delConfirmPassword' type='password' name='delConfirmPassword'>
              </div>
              <p class='help is-danger' id='delConfirmPasswordWarn'> </p>
            </div>



            <footer class='modal-card-foot'>
              <p class='control'>

                <input type='submit' class='button is-danger deleteAccIfValid' onclick="return confirm('Are you sure you wish to delete your account? THIS CANNOT BE UNDONE.')" id='deleteAccountButton' value='Delete Account' name='deleteAccountButton'>
                <button class='button cancelUpdate'>Cancel</button>
            </footer>
          </form>
        </section>

      </div>
    </div>




    <div class='myFooter' id='profileFooter'>
      <footer class='footer has-background-dark alsoMyFooter'>
        <div class='content has-text-centered has-text-white'>
          <p>
            <span id='boldFoot'>CSC7062 Project</span> by Jordan Brown (40282125).
          </p>
        </div>
      </footer>
    </div>



    <!--
     Error symbol/message that is displayed to the user if they try to access the page without their account having been approved, 
     rather than simply kicking them back to the dashboard without warning. 
     -->
  <?php
  } else {
    echo "
    <div class='container'>

      <div class='notApproved'>
        <h1 class='title'> Your account has not yet been approved. </h1>
      </div>

      <div class='notApproved'><a href='dashboard.php'><img src='images/error.png'></a></div>
      <div class='notApprovedClick'>(Please click the image to return to the dashboard)</div>


    </div>


    <div class='myFooter'>
      <footer class='footer has-background-dark alsoMyFooter' i>
        <div class='content has-text-centered has-text-white'>
          <p>
            <span id='boldFoot'>CSC7062 Project</span> by Jordan Brown (40282125).
          </p>
        </div>
      </footer>
    </div>";
  }
  ?>







</body>


</html>