<?php
session_start();
include("conn.php");
if ((isset($_SESSION['gymafi_userid'])) || isset($_SESSION['gymafi_coachid'])) {
  header("location: dashboard.php");
} else if (isset($_SESSION['gymafi_superadmin'])) {
  header("location: admin/superadmin.php");
}


/**
 * Captures posted data, sanitises it and if it meets the validation checks it will 
 * send the data to the database.
 */
if (isset($_POST['signup'])) {

  $username = $_POST['uname'];
  $sanitisedUser = $conn->real_escape_string(trim($username));
  $sanitisedPassword = $conn->real_escape_string(trim($_POST['pass']));
  $email = $_POST['email'];
  $sanitisedEmail = $conn->real_escape_string(trim($_POST['email']));
  if (is_numeric($_POST['telephoneNumber'])) {
    $sanitisedTelephone = $conn->real_escape_string(trim($_POST['telephoneNumber']));
  }
  if (!is_numeric($_POST['realName'])) {
    $sanitisedRealName = $conn->real_escape_string(trim($_POST['realName']));
  }
  $dateOfBirth  = $_POST['dateOfBirth'];
  $updatedDOB = date('Y-m-d', strtotime($dateOfBirth));
  $sanitisedDOB = $conn->real_escape_string(trim($updatedDOB));
  $sanitisedAddress = $conn->real_escape_string(trim($_POST['addLineOne']));
  if (!is_numeric($_POST['city'])) {
    $sanitisedCity = $conn->real_escape_string(trim($_POST['city']));
  }
  $sanitisedPostcode = $conn->real_escape_string(trim($_POST['postCode']));
  $sanitisedCoach = $conn->real_escape_string(trim($_POST['coachWanted']));




  /**
   * Determine if user already has an account, run database queries to determine if the username and email are already in the system.
   * If they are, displays an error to the user and prompts them to enter different details or to reset their password.
   * 
   */

  $checkExistingUser = "SELECT * FROM webdev_users WHERE username = '$username'";
  $checkExistingEmail = "SELECT * FROM webdev_users WHERE  email = '$email'";
  $existUserResult = $conn->query($checkExistingUser);
  $existEmailResult = $conn->query($checkExistingEmail);

  if (!$existUserResult) {
    echo $conn->error;
  }

  if (!$existEmailResult) {
    echo $conn->error;
  }

  $numUser = $existUserResult->num_rows;
  $numEmail = $existEmailResult->num_rows;
  // if returns any results, outputs an error as they already have registered.

  if (($numEmail > 0) && ($numUser > 0)) { // if both in use, display combined error
    $signUpError = "Email and username already in use. Please try different credentials or reset your password ";
  } else if ($numEmail > 0) { // if email in use, error for that
    $signUpError = "Email already in use. Please try a different email or reset your password ";
  } else if ($numUser > 0) { // if username is in use, error for that. 
    $signUpError = "Username already taken. Please try a different username or reset your password. ";
  }




  /*
  * Explodes DOB entered by user and a new date generated by server (today's date). 
  * If user DOB entered is < 18, does not allow sign up.
  * Adapted from <https://stackoverflow.com/questions/4529640/get-the-year-from-specified-date-php/4529680>
  */
  $todaysDate = date('Y-m-d');
  $yearOfDOB = explode('-', $dateOfBirth);
  $DOBYear = $yearOfDOB[0];
  $todayExplode = explode('-', $todaysDate);
  $todayYear = $todayExplode[0];
  $minimumYear = ($todayYear - 18);
  $maximumYear = 1940;


  /**
   * If fields are not null, and also meet additional validation such as ensuring the user is > 18 and the password contains required characters
   * it will then process the data and insert it into the database, ready for the coach to approve/deny the user.
   */
  if (
    !$sanitisedUser  == null && !$sanitisedPassword  == null && !$sanitisedEmail == null && !$dateOfBirth == null && !$sanitisedRealName  == null
    && !$sanitisedAddress  == null  && !$sanitisedCity == null && !$sanitisedPostcode  == null && !$sanitisedTelephone == null
    && !$sanitisedCoach == null && ctype_digit($sanitisedTelephone)
  ) { // ensuring non-null values are inserted


    if ($DOBYear > $minimumYear) {
      $signUpError = "Your details have not been submitted - you must be over 18.";
    } else if ($maximumYear > $DOBYear) {
      $signUpError = "Your details have not been submitted - invalid date of birth (1940 minimum).";
    } else if (preg_match('~[0-9]~', $sanitisedRealName)) {
      $signUpError = "Error with sign up - your name must only contain letters";
    } else if (preg_match('~[0-9]~', $sanitisedCity)) {
      $signUpError = "Error with sign up - your city must only contain letters";
    } else if ((strlen($sanitisedTelephone) < 10) || strlen($sanitisedTelephone) > 13) {
      $signUpError = "Error with sign up - telephone number out of range boundary. Must be between 10 - 13 digits.";
    } else if ((strlen($sanitisedUser) > 25)) {
      $signUpError = "Error with sign up - username  out of range boundary. Must be under 25 characters.";
    } else if ((strlen($sanitisedRealName) > 35)) {
      $signUpError = "Error with sign up - name  out of range boundary. Must be under 35 characters.";
    } else if ((strlen($sanitisedCity) > 35)) {
      $signUpError = "Error with sign up - city  out of range boundary. Must be under 35 characters.";
    } else if ((strlen($sanitisedEmail) > 35)) {
      $signUpError = "Error with sign up - email out of range boundary. Must be under 55 characters.";
    } else if ((strlen($sanitisedAddress) > 100)) {
      $signUpError = "Error with sign up - address  out of range boundary. Must be under 100 characters.";
    } else if ((strlen($sanitisedPostcode) > 10)) {
      $signUpError = "Error with sign up - postcode  out of range boundary. Must be under 10 characters.";
    } else if (strlen($sanitisedPassword) < 8 || strlen($sanitisedPassword) > 16) {
      $signUpError = "Error with sign up - password should be between 8 and 16 characters.";
      /**
       * Regex for password check from online guide
       * https://stackoverflow.com/questions/42467243/regex-strong-password-the-special-characters
       */
    } else if (!preg_match("/\d/", $sanitisedPassword)) {
      $signUpError = "Error with sign up - password should contain one digit at least.";
    } else if (!preg_match("/[A-Z]/", $sanitisedPassword)) {
      $signUpError = "Error with sign up - password should contain at least one uppercase Letter";
    } else if (!preg_match("/[a-z]/", $sanitisedPassword)) {
      $signUpError = "Error with sign up - password must contain at least one lowercase letter.";
    } else if (!preg_match("/\W/", $sanitisedPassword)) {
      $signUpError = "Error with sign up - password should contain at least one special character.";
    } else {


      // transaction adapted from online tutorial https://www.youtube.com/watch?v=CNt9HPqDIVc
      $conn->autocommit(false);

      $error = array();

      $a = $conn->query("INSERT INTO webdev_user_details (name, address, postcode, city, phone_number, coach, username)
VALUES ('$sanitisedRealName', '$sanitisedAddress', '$sanitisedPostcode', '$sanitisedCity', 
'$sanitisedTelephone', $sanitisedCoach, '$sanitisedUser');");
      if ($a == false) {
        array_push($error, 'Problem with pushing to db');
        echo $conn->error;
      }
      $b =  $conn->query("INSERT INTO webdev_users (username, password, email, role, date_of_birth, approved)
VALUES ('$sanitisedUser', AES_ENCRYPT('$sanitisedPassword', '09UYO2ELHJ290OYEH22098H9ty'), '$sanitisedEmail', 3, '$sanitisedDOB', 0);");
      if ($b == false) {
        array_push($error, 'Problem with pushing to db');
        echo $conn->error;
      }
      if (!empty($error)) {
        $conn->rollback();
        echo $conn->error;
      } else {
        $conn->commit();
        $signUpSuccess = "You have been registered. Sent to coach for approval.";
      }
    }
  } else if (!ctype_digit($sanitisedTelephone)) {
    $signUpError = "Error with sign up - telephone must be numeric";
  }
}


?>

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Gymafi | Sign Up</title>
  <link href="styles/bulma.css" rel="stylesheet">
  <link href="styles/gui.css" rel="stylesheet">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script src="script/myScript.js"></script>


</head>

<body class="has-background-grey-lighter">
  <!--If not logged in, displays login/sign up buttons. If logged in ,displays log out button. -->

  <nav class='navbar is-dark' role='navigation' aria-label='main navigation'>
    <div class='navbar-end'>
      <div class='navbar-item'>
        <div class='buttons loginButtons'>
          <a class='button is-primary' href='signup.php'>
            <strong>Sign up</strong>
          </a>
          <a class='button is-link' href='login.php'>
            <strong>Log in</strong>
          </a>
        </div>
      </div>
    </div>
  </nav>


  <section class="hero is-dark is-small">
    <div class="hero-body">
      <div class="container">
        <h1 class="title myTitle">
          Gymafi
        </h1>
        <h2 class="subtitle myTitle">
          Unlocking Your Potential
        </h2>
      </div>
    </div>
  </section>
  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">


    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu has-background-dark">
      <div class="navbar-start myNavPublic">
        <a class="navbar-item has-text-white" href='index.php'>
          Home
        </a>

        <a class="navbar-item has-text-white" href='aboutus.php'>
          About Us
        </a>

        <a class="navbar-item has-text-white" href='coaches.php'>
          Coaches
        </a>

        <a class="navbar-item has-text-white" href='contact.php'>
          Contact
        </a>

        <a class="navbar-item has-text-white" href='testimonials.php'>
          Testimonials
        </a>
      </div> <!-- end of navbarBasicExample-->


    </div>
  </nav>

  <?php
  $getContentOfPage = $conn->prepare("SELECT webdev_page_content.title,  webdev_page_content.content, 
webdev_page_content.content_2
FROM webdev_page_content
WHERE webdev_page_content.id = 14");
  $getContentOfPage->execute();
  $getContentOfPage->store_result();
  $getContentOfPage->bind_result($contentTitle, $contentOne, $contentTwo);
  $getContentOfPage->fetch();
  echo "
  <div id='signUpTitle'>
    <h2 class='title'>$contentTitle</h2>
    <h3 class='subtitle is-6'>
      <p>$contentOne</p>
      <p>$contentTwo</p>
    </h3>

  </div>
  <!--end of loginTitle -->";
  ?>

  <form action='signup.php' method='POST' id='signUpForm'>
    <div id="outerContain">
      <div id="loginBorder">
        <div id="innerContain ">


          <div class="columns">
            <div class="column"> </div>
            <div class="column loginCol">
              <div class="field">
                <label class="label">Username:</label>

                <p class="control has-icons-left">
                  <?php
                  /** 
                   * Attempts to display the previously posted value if form did not successfully get completed, else displays an empty input area
                   */
                  if (isset($sanitisedUser)) {
                    $entityUsername = htmlentities($sanitisedUser);
                    echo "<input class='input' type='text' id='userNameSign' value='$entityUsername' name='uname'>";
                  } else {
                    echo "<input class='input' type='text' id='userNameSign' placeholder='Username' name='uname'>";
                  }
                  ?>
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>

                </p>
              </div>
              <p class="help is-danger" id="userWarn">
              </p>
            </div> <!-- end of column-->
            <div class="column">
            </div> <!-- end of column-->
          </div> <!-- end of columns-->





          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Email:</label>
                <p class="control has-icons-left">
                  <?php
                  /** 
                   * Attempts to display the previously posted value if form did not successfully get completed, else displays an empty input area
                   */
                  if (isset($sanitisedEmail)) {
                    $email = htmlentities($sanitisedEmail);
                    echo "<input class='input' type='email' id='emailSign' value='$email' name='email'>";
                  } else {
                    echo "<input class='input' type='email' id='emailSign' placeholder='example@gmail.com' name='email'>";
                  }

                  ?>
                  <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                  </span>
                </p>
              </div>
              <p class="help is-danger" id="emailWarn">
              </p>
            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->


          </div> <!-- end of field-->

          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Password:</label>

                <p class="control has-icons-left">
                  <input class="input" type="password" id="passwordSign" placeholder="Password" name="pass">

                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>

                </p>
                <p>Password should be between 8-16 characters and contain one of the following: an uppercase and lowercase letter, a number and a special character.</p>
              </div>
              <p class="help is-danger" id="passWarn">
              </p>

            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->

          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Confirm Password:</label>
                <p class="control has-icons-left">
                  <input class="input" type="password" id="confirmPasswordSign" placeholder="Confirm password" name="confirmPass">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>

              <p class="help is-danger" id="confirmPassWarn">
              </p>


            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->

          <div class="columns">
            <div class="column"> </div>
            <div class="column loginCol">
              <div class="field loginCol">
                <label class="label">Full name:</label>

                <p class="control has-icons-left">
                  <?php
                  /** 
                   * Attempts to display the previously posted value if form did not successfully get completed, else displays an empty input area
                   */
                  if (isset($sanitisedRealName)) {
                    $realName = htmlentities($sanitisedRealName);
                    echo "<input class='input' type='text' id='realNameSign' value='$realName' name='realName'>";
                  } else {
                    echo "<input class='input' type='text' id='realNameSign' placeholder='Joe Bloggs' name='realName'>";
                  }
                  ?>
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>

                </p>
              </div>
              <p class="help is-danger" id="nameWarn">
              </p>
            </div> <!-- end of column-->


            <div class="column">
            </div> <!-- end of column-->


          </div> <!-- end of columns-->




          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Date of Birth:</label>
                <p class="control has-icons-left">
                  <input class="input" type="date" id="dob" placeholder="04-06-1996" name="dateOfBirth">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>

              <p class="help is-danger" id="dobWarn">
              </p>


            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->



          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Telephone Number:</label>
                <p class="control has-icons-left">
                  <?php
                  /** 
                   * Attempts to display the previously posted value if form did not successfully get completed, else displays an empty input area
                   */
                  if (isset($sanitisedTelephone)) {
                    $telephone = htmlentities($sanitisedTelephone);
                    echo "<input class='input' type='text' id='telephoneNo' value='$telephone' name='telephoneNumber'>";
                  } else {
                    echo "<input class='input' type='text' id='telephoneNo' placeholder='028927182712' name='telephoneNumber'>";
                  }
                  ?>
                  <span class="icon is-small is-left">
                    <i class="fas fa-phone"></i>
                  </span>
                </p>
              </div>

              <p class="help is-danger" id="telephoneWarn">
              </p>


            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->
          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Address:</label>
                <p class="control has-icons-left">
                  <?php
                  /** 
                   * Attempts to display the previously posted value if form did not successfully get completed, else displays an empty input area
                   */
                  if (isset($sanitisedAddress)) {
                    $addressLine = htmlentities($sanitisedAddress);
                    echo "<input class='input' type='text' id='addressLine' value='$addressLine' name='addLineOne'>";
                  } else {
                    echo "<input class='input' type='text' id='addressLine' placeholder='123 Fake Street' name='addLineOne'>";
                  }
                  ?>
                  <span class="icon is-small is-left">
                    <i class="fas fa-home"></i>
                  </span>
                </p>
              </div>


              <p class="help is-danger" id="addressWarn">
              </p>

            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->



          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">City:</label>
                <p class="control has-icons-left">

                  <?php
                  /** 
                   * Attempts to display the previously posted value if form did not successfully get completed, else displays an empty input area
                   */
                  if (isset($sanitisedCity)) {
                    $city = htmlentities($sanitisedCity);
                    echo "<input class='input' type='text' id='city' value='$city' name='city'>";
                  } else {
                    echo "<input class='input' type='text' id='city' placeholder='City' name='city'>";
                  }
                  ?>
                  <span class="icon is-small is-left">
                    <i class="fas fa-city"></i>
                  </span>
                </p>
              </div>


              <p class="help is-danger" id="cityWarn">
              </p>

            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->
          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Postcode:</label>
                <p class="control has-icons-left">
                  <?php
                  /** 
                   * Attempts to display the previously posted value if form did not successfully get completed, else displays an empty input area
                   */
                  if (isset($sanitisedPostcode)) {
                    $postCode = htmlentities($sanitisedPostcode);
                    echo " <input class='input' type='text' id='postCode' value='$postCode' name='postCode'>";
                  } else {
                    echo " <input class='input' type='text' id='postCode' placeholder='Postcode' name='postCode'>";
                  }
                  ?>
                  <span class="icon is-small is-left">
                    <i class="fas fa-home"></i>
                  </span>
                </p>
              </div>


              <p class="help is-danger" id="postcodeWarn">
              </p>

            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->



          <div class="columns">
            <div class="column"> </div>
            <div class="column">
              <div class="field">
                <label class="label">Desired coach:</label>
                <div class="control">
                  <div class='select'>
                    <select name='coachWanted'>
                      <?php
                      // grab all coaches
                      $getcoaches = "SELECT * FROM webdev_coach;";
                      $executeGetCoaches = $conn->query($getcoaches);

                      if (!$executeGetCoaches) {
                        echo $conn->error;
                      }

                      while ($row = $executeGetCoaches->fetch_assoc()) {
                        $name = $row['name'];
                        $coachID = $row['id'];
                        $area = $row['area'];
                        echo "<option value='$coachID'> $name ($area) </option>";
                      }

                      ?>
                    </select>
                  </div>
                </div>
              </div>



            </div> <!-- end of column-->

            <div class="column">
            </div> <!-- end of column-->

          </div> <!-- end of columns-->




          <div class="columns">
            <div class="column"> </div>
            <div class="column"> </div>
            <div class="column"> </div>
            <div class="column">

              <a class="button is-danger formButtonsSignUp" id='resetSign'>
                Reset
              </a>

            </div>

            <div class="column">
              <div class="field">
                <p class="control">
                  <input type='submit' class="button is-primary formButtonsSignUp buttonSignUpIfValid" value="Sign Up" name="signup">

                  </button>
                </p>
              </div> <!-- end of field-->
            </div> <!-- end of column-->



            <div class="column"> </div>
            <div class="column"> </div>

          </div> <!-- end of columns-->
  </form>

  <!-- if wrong login details, displays error-->
  <?php
  if (isset($signUpError)) {
    echo "<p class='regError'>$signUpError</p>";
  } else if (isset($signUpSuccess)) {
    echo "<p class='regSuccess'>$signUpSuccess</p>";
  }

  ?>



  </div>
  </div> <!-- end of innerContainer-->
  </div> <!-- end of outerContainer-->



  <div class="myFooter">
    <footer class="footer has-background-dark alsoMyFooter">
      <div class="content has-text-centered has-text-white">
        <p>
          <span id="boldFoot">CSC7062 Project</span> by Jordan Brown (40282125).
        </p>
      </div>
    </footer>
  </div>
</body>


</html>